### ISSUE TITLE
Export Dash Table as a PDF file

### ISSUE THREAD

**Issue by Sashanka-Shekhar-Behera** [AnnMarieW/dash-app-gallery#151]
Hey There I'm trying to export the dash table in the pdf format and generated a function as follows:

` def generate_pdf(n_clicks):
    pdf = FPDF()  # Create a new PDF document

    # Set up the PDF document
    pdf.add_page()
    pdf.set_font("Arial", size=8)

    # Calculate the column widths based on the PDF page size
    page_width = pdf.w - 2 * pdf.l_margin
    col_widths = [page_width / len(data.columns)] * len(data.columns)

    # Add the table headers to the PDF
    for col, col_width in zip(data.columns, col_widths):
        pdf.cell(col_width, 10, col, 1)
    pdf.ln()

    # Add the table rows to the PDF
    table_data = data.to_dict('records')
    for row in table_data:
        for col, col_width in zip(data.columns, col_widths):
            cell_text = str(row[col])
            pdf.cell(col_width, 10, cell_text, 1)
        pdf.ln()

    # Generate the PDF file
    pdf_bytes = pdf.output(dest="S").encode("latin-1")

    return dcc.send_bytes(pdf_bytes, "mytable.pdf")  # Send the PDF bytes for download`
    
in this code I was able to export the dash table as a PDF file but the exported table cell content gets out of column width. So I want to text wrap the cell content within the column width... Anyone please help with this.
A updated code will be good. Thank You in Advance!

**Comment by Coding-with-Adam** [comment]
hi @Sashanka-Shekhar-Behera 
This is a great question for the [Plotly community forum](https://community.plotly.com/). Sorry we missed this.
