### ISSUE TITLE
cannot import name 'ctx' from 'dash'

### ISSUE THREAD

**Issue by rpanai** [AnnMarieW/dash-app-gallery#43]
I installed the requirements but when I try to run the app I got this error.

**Comment by AnnMarieW** [comment]
Hi @rpanai.  Thanks for reporting. That was new in dash 2.4.1  We should add that to the `requirements.txt`

**Comment by rpanai** [comment]
do you want me to do a pr?

**Comment by someshfengde** [comment]
Hi @rpanai  I'll update requirements.txt shortly thanks for letting us know

**Comment by rpanai** [comment]
@someshfengde nice. Keep in mind we need `dash-mantine-components` too
