### ISSUE TITLE
Tolga - app that has a dcc and a choropleth map

### ISSUE THREAD

**Issue by Coding-with-Adam** [AnnMarieW/dash-app-gallery#5]
dash core component tied to a choropleth graph

- [ ] Layout- 1row:1col;  1row:2col;  2row:1col;  3row:1col;  multiple row and col
- [ ] Callback- 1input:1output;  2input:1output;  1input:2output;  Multiple output input 
- [ ] Components - dropdown, checklist, DataTable, RadioItem,
- [ ] Data set - sports, geology, manufacturing, finance, general
- [ ] Graph- Bar, Line, Histogram, Scatter, Pie, Candle, etc

**Comment by tolgahancepel** [comment]
Added the population density application with a choropleth, and created a pull request.

**Comment by someshfengde** [comment]
wow @tolgahancepel  congrats you wrote the first app :)

**Comment by Coding-with-Adam** [comment]
Done. population-density.py
