### ISSUE TITLE
Somesh - app with two buttons and Daq LEDdisplay

### ISSUE THREAD

**Issue by Coding-with-Adam** [AnnMarieW/dash-app-gallery#7]
Stopwatch app counting seconds (daq.LEDDisplay), with a start and stop button

- [ ] Layout- 1row:1col;  1row:2col;  2row:1col;  3row:1col;  multiple row and col
- [ ] Callback- 1input:1output;  2input:1output;  1input:2output;  Multiple output input 
- [ ] Components - dropdown, checklist, DataTable, RadioItem, etc.
- [ ] Data set - sports, geology, manufacturing, finance, general
- [ ] Graph- Bar, Line, Histogram, Scatter, Pie, Candle, etc

**Comment by someshfengde** [comment]
I've submitted PR for this 
It's working as expected 😄
