### ISSUE TITLE
Somesh- app with 2 sliders and a Graph 

### ISSUE THREAD

**Issue by Coding-with-Adam** [AnnMarieW/dash-app-gallery#9]
Somesh- 2 sliders that update the width and height of a dcc.Graph 

- [ ] Layout- 1row:1col;  1row:2col;  2row:1col;  3row:1col;  multiple row and col
- [ ] Callback- 1input:1output;  2input:1output;  1input:2output;  Multiple output input 
- [ ] Components - dropdown, checklist, DataTable, RadioItem, etc.
- [ ] Data set - sports, geology, manufacturing, finance, general
- [ ] Graph- Bar, Line, Histogram, Scatter, Pie, Candle, etc

**Comment by someshfengde** [comment]
Yes sure I'll update it soon I just noticed it

**Comment by AnnMarieW** [comment]
Hi @someshfengde    Before you do this one, let me check with Adam - there is already an app that adjusts the width with a slider:  https://github.com/AnnMarieW/dash-app-gallery/blob/main/examples/setting-graph-size.py

**Comment by someshfengde** [comment]
> Hi @someshfengde    Before you do this one, let me check with Adam - there is already an app that adjusts the width with a slider:  https://github.com/AnnMarieW/dash-app-gallery/blob/main/examples/setting-graph-size.py

Yes he has to close this issue
